defaults:
  - score_math
  - _self_

cache_dir: '/home/pramit/hrl-nips-work/hrl-reasoning/.cache'
save_path: '/home/pramit/hrl-nips-work/hrl-reasoning/.saved_models/smart_score'

checkpoint_path: null
use_smart_corrections: true
correction_model_path: null   

# use a meaningful run name for tracking
run_name: 'smart-score-math'
project_name: 'score_math'