defaults:
  - default
  - _self_

# system paths
cache_dir: '/home/pramit/hrl-nips-work/hrl-reasoning/.cache'
save_path: '/home/pramit/hrl-nips-work/hrl-reasoning/.saved_models/score_math'

# checkpoint
checkpoint_path: null

# env
env_name: math
env_load_path: null

# model settings
agent_type: "score"
policy_lm: "meta-llama/Llama-3.2-1B-Instruct"
critic_lm: "roberta-base"
max_new_tokens: 512
max_tokens: 512
temperature: 0.7
do_sample: true
use_lora: true
huggingface_token: "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"

# training hyperparameters
capacity: 100000      # Replay buffer size
rollout_size: 128     # Number of parallel environments
eval_size: 8          # Number of trajectories for evaluation
batch_size: 4         # Training batch size
iterations: 150        # Total number of iterations
epochs: 10            # Times to train critic on each batch
actor_epochs: 4       # Times to train actor on each batch
warmup_iter: 20        # Initial iterations without policy updates
grad_accum_steps: 16
critic_lr: 2e-5
lm_lr: 5e-6
stage1_steps: 75
stage2_steps: 75
total_steps: 150

# algorithm parameters
gamma: 0.95           # Discount factor
tau: 0.1              # Soft update parameter
max_grad_norm: 1.0    # Gradient clipping


use_smart_corrections: false
save_freq: 15          
eval_freq: 25          

# wandb logging
use_wandb: true
project_name: 'score_math'
run_name: 'score-math-reinforce-kl'